# Original from envoyproject/envoy:examples/front-proxy/docker-compose.yml
# Modified by Instana:
# - use instana-opentracing dockerfiles
version: '2'
services:

  service:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      pocmesh:
        aliases:
          - java-service
    environment:
      - PORT=8080
      - INSTANA_DEV=1
      - INSTANA_AGENT_HOST=instana-agent
    ports:
      - 8080:8080
    expose:
      - "8080"

  agent:
    image: instana/agent
    pid: "host"
    privileged: true
    volumes:
# When this file is mounted in the agent container, all the trace data sent by the agent
# to the backend will be logged in a /opt/instana/agent/data/log/traces-XXX.log
# DO NOT TURN IT ON IN PRODUCTION: MASSIVE OVERHEAD
#      - ./com.instana.agent.main.sender.File.cfg:/opt/instana/agent/etc/instana/com.instana.agent.main.sender.File.cfg
      - ./configuration.yaml:/root/configuration.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
    networks:
      pocmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=<FILL THIS>
      - INSTANA_AGENT_ENDPOINT_PORT=<FILL THIS>
      - INSTANA_AGENT_KEY=<FILL THIS>
      # TODO Edit the lines above ^^^^^^^
      - INSTANA_AGENT_ZONE=rewe-demo
    expose:
      - "42699"

networks:
  pocmesh: {}